import type { ResumeData } from './models';

export const sampleResumeData: ResumeData = {
  id: '1',
  personal: {
    firstName: 'Alex',
    lastName: 'Johnson',
    title: 'Full Stack Developer',
    summary: 'Passionate full stack developer with over 5 years of experience building scalable web applications using modern JavaScript frameworks. Specializing in React, Node.js, and cloud infrastructure. Committed to writing clean, maintainable code and delivering exceptional user experiences.',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  contact: {
    email: 'alex.johnson@example.com',
    phone: '(555) 123-4567',
    address: '123 Tech Lane',
    city: 'San Francisco',
    state: 'CA',
    zip: '94105',
    country: 'USA',
    website: 'alexjohnson.dev',
    linkedin: 'linkedin.com/in/alexjohnson',
    github: 'github.com/alexjohnson',
    twitter: 'twitter.com/alexjohnson',
  },
  experience: [
    {
      id: 'exp1',
      company: 'Tech Innovations Inc.',
      position: 'Senior Full Stack Developer',
      startDate: '2020-03',
      endDate: 'Present',
      description: 'Lead developer for the company\'s flagship SaaS product serving over 10,000 customers.',
      location: 'San Francisco, CA',
      highlights: [
        'Architected and implemented a microservices-based backend that improved system reliability by 35%',
        'Reduced page load times by 40% through frontend optimizations and code splitting',
        'Mentored junior developers and led code reviews for a team of 8 engineers',
        'Implemented CI/CD pipelines that reduced deployment time from hours to minutes',
      ],
    },
    {
      id: 'exp2',
      company: 'DataSphere Solutions',
      position: 'Frontend Developer',
      startDate: '2018-06',
      endDate: '2020-02',
      description: 'Worked on the customer-facing dashboard for data analytics tools.',
      location: 'Oakland, CA',
      highlights: [
        'Developed responsive data visualization components using D3.js and React',
        'Collaborated with UX designers to implement intuitive interfaces for complex data interactions',
        'Refactored legacy jQuery code to modern React, improving maintainability',
        'Participated in agile development process with bi-weekly sprints',
      ],
    },
    {
      id: 'exp3',
      company: 'WebStart Studios',
      position: 'Junior Web Developer',
      startDate: '2016-09',
      endDate: '2018-05',
      description: 'Developed websites and web applications for various clients across industries.',
      location: 'San Jose, CA',
      highlights: [
        'Built custom WordPress themes and plugins for small to medium businesses',
        'Implemented responsive designs that work across desktop, tablet, and mobile devices',
        'Optimized website performance and SEO for higher search rankings',
        'Coordinated with project managers to ensure timely delivery of client projects',
      ],
    },
  ],
  education: [
    {
      id: 'edu1',
      school: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science',
      startDate: '2012-09',
      endDate: '2016-05',
      description: 'Graduated with honors. Specialized in software engineering and human-computer interaction.',
      location: 'Berkeley, CA',
    },
    {
      id: 'edu2',
      school: 'Coding Academy',
      degree: 'Certificate',
      fieldOfStudy: 'Full Stack Web Development',
      startDate: '2016-06',
      endDate: '2016-08',
      description: 'Intensive coding bootcamp focusing on modern web technologies.',
      location: 'San Francisco, CA',
    },
  ],
  skills: [
    { id: 'skill1', name: 'JavaScript', level: 5 },
    { id: 'skill2', name: 'TypeScript', level: 4 },
    { id: 'skill3', name: 'React', level: 5 },
    { id: 'skill4', name: 'Node.js', level: 4 },
    { id: 'skill5', name: 'Express', level: 4 },
    { id: 'skill6', name: 'MongoDB', level: 3 },
    { id: 'skill7', name: 'PostgreSQL', level: 4 },
    { id: 'skill8', name: 'AWS', level: 3 },
    { id: 'skill9', name: 'Docker', level: 3 },
    { id: 'skill10', name: 'Git', level: 5 },
    { id: 'skill11', name: 'CI/CD', level: 4 },
    { id: 'skill12', name: 'HTML/CSS', level: 5 },
  ],
  languages: [
    { id: 'lang1', name: 'English', proficiency: 'Native' },
    { id: 'lang2', name: 'Spanish', proficiency: 'Conversational' },
    { id: 'lang3', name: 'French', proficiency: 'Basic' },
  ],
  projects: [
    {
      id: 'proj1',
      name: 'EcoTracker',
      description: 'A mobile app for tracking personal carbon footprint and suggesting eco-friendly alternatives.',
      url: 'github.com/alexjohnson/ecotracker',
      startDate: '2019-04',
      endDate: '2019-12',
      highlights: [
        'Built with React Native for cross-platform compatibility',
        'Implemented gamification features to encourage user engagement',
        'Integrated with public transportation APIs for route suggestions',
        'Featured in local environmental newsletter with 10,000 subscribers',
      ],
    },
    {
      id: 'proj2',
      name: 'DevConnect',
      description: 'Open-source platform for developers to share projects and collaborate.',
      url: 'devconnect.io',
      startDate: '2020-07',
      endDate: '2021-01',
      highlights: [
        'Built using the MERN stack (MongoDB, Express, React, Node.js)',
        'Implemented real-time chat using Socket.io',
        'Designed REST API with comprehensive documentation',
        'Over 500 active users within first three months',
      ],
    },
  ],
  certifications: [
    {
      id: 'cert1',
      name: 'AWS Certified Solutions Architect',
      organization: 'Amazon Web Services',
      date: '2021-05',
      url: 'aws.amazon.com/certification',
    },
    {
      id: 'cert2',
      name: 'Professional Scrum Master I',
      organization: 'Scrum.org',
      date: '2020-01',
      url: 'scrum.org/certificates',
    },
  ],
  customSections: [
    {
      id: 'custom1',
      title: 'Volunteer Experience',
      items: [
        {
          id: 'vol1',
          content: 'Code for America, Technical Volunteer (2019-Present) - Developing web applications for local government services to improve community access.',
        },
        {
          id: 'vol2',
          content: 'Tech Mentorship Program, Mentor (2018-Present) - Providing guidance to underrepresented groups entering the tech industry.',
        },
      ],
    },
    {
      id: 'custom2',
      title: 'Publications',
      items: [
        {
          id: 'pub1',
          content: '"Modern React Patterns," Tech Journal, March 2021 - Comprehensive overview of advanced React design patterns.',
        },
        {
          id: 'pub2',
          content: '"Optimizing Web Performance," Frontend Weekly, October 2020 - Strategies for improving load times and user experience.',
        },
      ],
    },
  ],
};
